name: fudmentor
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  sqflite: ^2.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  url_launcher: ^6.0.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
     - assets/background_image.jpg
     - assets/PngItem_2829738.png
     - assets/download.png
     - assets/6769264_60111.jpg
     - assets/7309670.jpg
     - assets/7309681.jpg
     - assets/9334398.jpg
     - assets/9723582.jpg
     - assets/7309670.jpg
     - assets/6769264_60111.jpg
     - assets/7309681.jpg
     - assets/9723582.jpg
     - assets/9334398.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
